### ISSUE TITLE
【我】账号用户名显示异常

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#39]
机型：iPhoneSE Safari
步骤：
1、后台账号A：15608052662 一川
2、账号B：15608052663 二川
3、账号C：15608052664 三川
结果：账号B、账号C登录后在“我”里显示的是账号A的用户名“一川”
高复现率
预期结果：正确显示账号用户名

**Comment by boxshadow** [comment]
has been fixed
