### ISSUE TITLE
【消息-赞过的】下拉刷新赞列表时出现如图异常显示

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#42]
机型：iPhoneSE Safari/红米
步骤：消息-赞过的
结果：在“没有更多了”上按住然后下拉出现如图效果
![image](https://cloud.githubusercontent.com/assets/23622721/25603126/d0f27d08-2f2b-11e7-9dce-128a6ca8d489.png)

**Comment by boxshadow** [comment]
fixed
