### ISSUE TITLE
【首页-最新-动态详情】具有单张图片的动态详情页面排版有误

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#44]
机型：iPhoneSE Safari
步骤：登录-首页--最新-动态详情（单张图片）
结果：单张图片的动态详情，图片影响到整个页面的排版布局
![image](https://cloud.githubusercontent.com/assets/23622721/25688477/0cb48408-30b2-11e7-8c1c-ebfb32946089.png)

**Comment by boxshadow** [comment]
fixed
