### ISSUE TITLE
【忘记密码】获取验证码出现的位置有误

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#46]
机型：iPhoneSE Safari/谷歌
步骤：忘记密码
结果：获取验证码出现在验证码输入框后面
预期结果：参照App，应在手机号输入框后面展示“获取验证码”

**Comment by HuangYachuan** [comment]
注册中“获取验证码”的位置亦有误

**Comment by boxshadow** [comment]
位置为故意调整，验证码只有4位数字，手机11位，如果出现在手机号码输入框后方，会导致输入框和可操作图标无法正常排版
