### ISSUE TITLE
【登录】“找回密码”应改为“忘记密码”

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#47]
机型：vivo
步骤：登录
结果：右下角显示“找回密码”
预期结果：参照App，“找回密码”应改为“忘记密码”

**Comment by HuangYachuan** [comment]
PS:登录界面
手机号中的占位符应为“输入11位手机号”
密码中的占位符应为“输入6位以上登录密码”

**Comment by boxshadow** [comment]
has been fixed
