### ISSUE TITLE
【首页-最新-动态详情】加载小蓝点位置需调整

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#50]
机型：iPhoneSE Safari/谷歌
步骤：首页进入一个动态详情
结果：加载动态详情时，小蓝点出现的位置未居中且偏右下
![image](https://cloud.githubusercontent.com/assets/23622721/25937356/f551330e-365d-11e7-923b-f315d48def02.png)

预期结果：调整位置

**Comment by boxshadow** [comment]
has been fixed

**Comment by peicaichi** [comment]
当前位置还是歪着的
配图：
![image](https://cloud.githubusercontent.com/assets/22809873/26236303/3e774c0e-3ca2-11e7-9d80-5b53ad7ad894.png)

**Comment by boxshadow** [comment]
has been fixed
