### ISSUE TITLE
【我-个人资料】城市、简介编辑后保存“完成”未变为灰色

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#51]
机型：iPhoneSE Safari/谷歌
步骤：我-个人资料，单独修改城市/简介后点击“完成”
结果：“完成”按钮未熄灭，依然是蓝色，可以继续点击完成反复保存
预期结果：城市/简介编辑保存后，“完成”变为灰色且锁死

**Comment by boxshadow** [comment]
fixed
