### ISSUE TITLE
【我-个人主页】粉丝与关注的位置应对调

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#52]
机型：iPhoneSE Safari/谷歌
步骤：我-个人主页
结果：粉丝与关注的位置反了
预期结果：参照App，从左到右为“关注  粉丝”

PS：X条动态，动态条的底色过深

**Comment by boxshadow** [comment]
has been fixed

**Comment by boxshadow** [comment]
has been fixed

**Comment by peicaichi** [comment]
个人主页的X条动态消失不见了
配图：
![image](https://cloud.githubusercontent.com/assets/22809873/26235437/b32093f8-3c9d-11e7-86cb-5873e67da621.png)

**Comment by boxshadow** [comment]
has been fixed
