### ISSUE TITLE
【首页-最新】动态标题内容较长时文字过于贴近屏幕右侧

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#56]
机型：iPhoneSE Safari/谷歌
步骤：首页-最新
结果：当一条动态的标题、内容文字较长时，一行文字末端过于贴近屏幕右侧
![image](https://cloud.githubusercontent.com/assets/23622721/25941409/f52a8480-366b-11e7-948e-1b3560db1583.png)

预期结果：参照App，适度与边屏保持距离

**Comment by boxshadow** [comment]
fixed
