### ISSUE TITLE
【我-收藏】收藏列表取消一个收藏后下拉刷新依然显示被取消的

### ISSUE THREAD

**Issue by HuangYachuan** [boxshadow/plus-component-web#58]
机型：iPhoneSE Safari/谷歌
步骤：我-收藏-收藏列表，进入一条动态的动态详情，取消收藏，点击左上角返回，下拉刷新收藏列表
结果：被取消收藏的动态下拉刷新后依然显示在列表中，需要刷新浏览器页面被取消的才消失

**Comment by boxshadow** [comment]
has been fixed
