### ISSUE TITLE
【首页-动态详情】显示发布时间应显示在一排，当前显示了两排

### ISSUE THREAD

**Issue by peicaichi** [boxshadow/plus-component-web#72]
机型：iPhone6s 微信浏览器
结果：动态详情的发布时间换行显示了，应显示一排
配图：
![image](https://cloud.githubusercontent.com/assets/22809873/26236371/a66989da-3ca2-11e7-92b2-b8a78ba69b6d.png)

**Comment by boxshadow** [comment]
has been fixed
