### ISSUE TITLE
横方向的照片，缩略图展示是正确的，但是打开大图方向就错了

### ISSUE THREAD

**Issue by hantianlong** [boxshadow/plus-component-web#73]
![image](https://cloud.githubusercontent.com/assets/28078379/26236684/3d032ecc-3ca4-11e7-963b-f89d7fc0217c.png)
![image](https://cloud.githubusercontent.com/assets/28078379/26236689/43878b4e-3ca4-11e7-9c03-e3375fd879e2.png)

**Comment by boxshadow** [comment]
has been fixed
