### ISSUE TITLE
消息-点赞列表，头像没出来

### ISSUE THREAD

**Issue by hantianlong** [boxshadow/plus-component-web#74]
![image](https://cloud.githubusercontent.com/assets/28078379/26236861/0e968aec-3ca5-11e7-9d6a-7adc5dc2075c.png)

**Comment by boxshadow** [comment]
这里不是头像 是动态中的一张图，如果有图显示图片，没图显示文字

**Comment by peicaichi** [comment]
依旧未显示图片

**Comment by boxshadow** [comment]
这个动态有图？

**Comment by boxshadow** [comment]
bug for server
