### ISSUE TITLE
频道列表，当未订阅的时候，没有缺省图，放置同APP端的缺省图

### ISSUE THREAD

**Issue by hantianlong** [boxshadow/plus-component-web#92]
![1](https://user-images.githubusercontent.com/28078379/27780317-c5de5f4a-5ffa-11e7-8022-d13166f9081f.png)
![2](https://user-images.githubusercontent.com/28078379/27780318-c5efaaf2-5ffa-11e7-8931-a5a27a41aae1.jpg)

**Comment by boxshadow** [comment]
has been fixed
